void LCD_Clear(void);
void LCD_WriteStr(char *, char);
void LCD_Shift_Right(void);
void LCD_SetBackLight_On(void);
void LCD_SetBackLight_Off(void);
void LCD_SetBackLight_Brightness(char);
void LCD_MoveCursor_Forward(void);
void LCD_MoveCursor_Backward(void);
void LCD_BlinkBlockCursor_On();
void LCD_BlinkBlockCursor_Off();
void LCD_UnderLineCursor_On();
void LCD_UnderLineCursor_Off();
void LCD_Display_On();
void LCD_Display_Off();
void LCD_SetContrast(char);
void LCD_MoveCursor_Right();
void LCD_MoveCursor_Left();
void LCD_Shift_Up();
void LCD_Shift_Down();
void LCD_SetCursor_Position(char, char);
